# Site settings
title: Sean Park

# Contact
phone: "(412) 265 - 8129" # This is my real number. You should text me.
email: "seanpark1107@gmail.com" # This is my real email address. Please don't email me.

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

collections:
  projects:
    output: true
  experiences:
    sort_by: start_year
    output: true

defaults:
  -
    scope:
      path: ""
      type: "experiences"
    values:
      layout: "experience"
